/**
 * Property 7: CSS custom properties use sq prefix
 *
 * For any CSS custom property generated by the Token Pipeline, the property
 * name should match the pattern `--sq-{category}-{name}` (starting with `--sq-`).
 *
 * We parse `src/generated/_custom-properties.scss` and verify every custom
 * property declaration starts with `--sq-`.
 *
 * Feature: design-system-restructure, Property 7: CSS custom properties use sq prefix
 * Validates: Requirements 4.2, 8.2
 */
import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import fs from 'node:fs';

// ── Helpers ─────────────────────────────────────────────

const CUSTOM_PROPERTIES_FILE = 'src/generated/_custom-properties.scss';

/**
 * Pattern to extract CSS custom property declarations from the generated file.
 * Matches lines like `  --sq-color-brand-warm-black: #281805;`
 */
const CUSTOM_PROPERTY_RE = /^\s*(--[\w-]+)\s*:/;

/**
 * Parse the generated custom properties file and return an array of
 * { name, line } objects for each CSS custom property declaration found.
 */
function extractCustomProperties(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const properties = [];

  for (let i = 0; i < lines.length; i++) {
    const match = lines[i].match(CUSTOM_PROPERTY_RE);
    if (match) {
      properties.push({ name: match[1], line: i + 1 });
    }
  }

  return properties;
}

// ── Property Test ───────────────────────────────────────

describe('Feature: design-system-restructure, Property 7: CSS custom properties use sq prefix', () => {
  it('should have all custom properties starting with --sq-', () => {
    /**
     * Validates: Requirements 4.2, 8.2
     */
    const properties = extractCustomProperties(CUSTOM_PROPERTIES_FILE);

    // Ensure we actually found custom properties to test
    expect(properties.length).toBeGreaterThan(0);

    fc.assert(
      fc.property(
        fc.constantFrom(...properties),
        ({ name, line }) => {
          expect(
            name.startsWith('--sq-'),
            `Custom property "${name}" on line ${line} does not start with "--sq-". ` +
            `All generated CSS custom properties must use the "sq" prefix.`,
          ).toBe(true);
        },
      ),
      { numRuns: Math.max(100, properties.length * 5) },
    );
  });
});
