/**
 * Property 11: All paths use kebab-case
 *
 * For any directory name or file name in the new `src/` directories of the
 * restructured design system, the name should match the kebab-case pattern:
 *   ^[_]?[a-z][a-z0-9]*(-[a-z0-9]+)*(\.[a-z]+)?$
 *
 * Leading underscores are allowed (SCSS partials like `_typography.scss`).
 * File extensions are allowed. Only the NEW directories are scanned (not old
 * numeric-prefixed dirs that still exist during the transition).
 *
 * Feature: design-system-restructure, Property 11: All paths use kebab-case
 * Validates: Requirements 8.1
 */
import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import fs from 'node:fs';
import path from 'node:path';

// ── Helpers ─────────────────────────────────────────────

/** The new top-level directories to scan. */
const NEW_DIRECTORIES = [
  'src/base',
  'src/components',
  'src/utilities',
  'src/vendor',
  'src/mixins',
  'src/compat',
  'src/generated',
];

/**
 * Kebab-case pattern:
 * - Optional leading underscore (SCSS partials)
 * - Starts with a lowercase letter
 * - Followed by lowercase letters or digits
 * - Optionally followed by hyphen-separated segments of lowercase letters/digits
 * - Optionally followed by one or more dot-separated file extensions (e.g., .js.map)
 */
const KEBAB_CASE_RE = /^[_]?[a-z][a-z0-9]*(-[a-z0-9]+)*(\.[a-z0-9]+)*$/;

/**
 * Recursively collect all file and directory names under a given root.
 * Excludes `node_modules/` directories, `.gitkeep` files, and build artifacts
 * generated by webpack (compiled .js, .css, .map, .LICENSE.txt files in
 * component directories).
 * Returns an array of { fullPath, name } objects.
 */
function collectEntries(root) {
  const results = [];

  if (!fs.existsSync(root)) return results;

  /** Build artifacts to skip (generated by webpack into component dirs) */
  const BUILD_ARTIFACT_RE = /\.(js|css|js\.map|css\.map|LICENSE\.txt)$/;

  const entries = fs.readdirSync(root, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === 'node_modules') continue;
    if (entry.name === '.gitkeep') continue;

    const fullPath = path.join(root, entry.name);

    // Skip build artifacts in component directories
    if (!entry.isDirectory() && root.includes('src/components/') && BUILD_ARTIFACT_RE.test(entry.name)) {
      continue;
    }

    results.push({ fullPath, name: entry.name });

    if (entry.isDirectory()) {
      results.push(...collectEntries(fullPath));
    }
  }

  return results;
}

/**
 * Collect all file and directory names from the new directory structure.
 */
function getAllNewEntries() {
  const allEntries = [];
  for (const dir of NEW_DIRECTORIES) {
    if (fs.existsSync(dir)) {
      // Include the top-level directory name itself
      allEntries.push({ fullPath: dir, name: path.basename(dir) });
      allEntries.push(...collectEntries(dir));
    }
  }
  return allEntries;
}

// ── Property Test ───────────────────────────────────────

describe('Feature: design-system-restructure, Property 11: All paths use kebab-case', () => {
  it('should have all file and directory names in kebab-case', () => {
    /**
     * Validates: Requirements 8.1
     */
    const allEntries = getAllNewEntries();

    // Ensure we actually found entries to test
    expect(allEntries.length).toBeGreaterThan(0);

    fc.assert(
      fc.property(
        fc.constantFrom(...allEntries),
        ({ fullPath, name }) => {
          expect(
            KEBAB_CASE_RE.test(name),
            `"${fullPath}" has name "${name}" which does not match kebab-case pattern ` +
            `${KEBAB_CASE_RE}. Names should be lowercase, hyphen-separated, with optional ` +
            `leading underscore and file extension.`,
          ).toBe(true);
        },
      ),
      { numRuns: Math.max(100, allEntries.length * 5) },
    );
  });
});
